---
- op: add
  path: /spec/valuesFrom
  value:
    - kind: ConfigMap
      name: keycloak-values
      valuesKey: values.yaml
    - kind: Secret
      name: keycloak-secrets-values
      valuesKey: secrets.values.yaml
