web:
    config:
        authentication:
            oauth2:
                clientID: ENC[AES256_GCM,data:IhFTd+8=,iv:Petf92M/iI7ZuRGSSwjH2ZV4hNCXD8NETfWbbvagT1I=,tag:sDw1QHFFaDC+dpXZwOhaAQ==,type:str]
                clientSecret: ENC[AES256_GCM,data:MDTnk44fgsIYDoiSuxggX3dIqKCxOFKIXXXv5QyjQmY=,iv:OY7DJcuxET6HHkQbX7/GSwTfOD12shMVuvxx9hdgZrs=,tag:4t60PZb/EKKlEEvJzg7NpQ==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdlI2WnYva0RSdE5GTDht
            SEJSV2ZQK1VNRzREQUtsYWFSeTViRWdidGh3CkVDTVVjbjIwZjNYTHNDV3pNZDJp
            RGRvSkpPRm1URHp2UERMMllkTGhWYVEKLS0tIFdYL1phMDN1THc2Nm5HdWlDZ3VJ
            UkFja3FDeG1TUWo0ZmFUdU4wK3F3OG8KM8tfnq3DFmZs2+JuFPb/hMpLN3Alsepo
            nPNexULoqOHfAPZq8VBSQ01dQ5BcNfoRZb2wgPwEOLWsQWyY7LVx+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T21:29:03Z"
    mac: ENC[AES256_GCM,data:f1bpa4AURyrdVi3AJhRR/T2A1j5Y+/Cgfy/gWHP2QGa65Y8P3OYpf35KI7scwl7g22YF40xIpKuTWjWcDqiFFcKtS5dsKyTI57bDtkux9CdvYHWHoyfEiiWg5d7JaS9vPeMqu4ZmZNqoNaF54XQtdZVo2zgk2Bfnr5Ju8g8UTw4=,iv:HnOPsIt9e+3ZEQ04nHPuJm9wLSIt/ZUs1HCNnuA887I=,tag:Rqv65c7zpi6S4Jakfr6wiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
