---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../../base/flux-operator
  - secret.yaml
configMapGenerator:
  - name: flux-operator-values
    namespace: flux-system
    files:
      - values.yaml
secretGenerator:
  - name: flux-operator-secrets-values
    namespace: flux-system
    files:
      - secrets.values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: "disabled"
patches:
  - path: patches/ocirepository.yaml
  - path: patches/helmrelease.yaml
