apiVersion: v1
kind: Secret
metadata:
    name: nix-docker-oci
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mCjrbQJdhoaVXbjKOo5Uq4w6Pvb+QEr5SA7M9QxT8ril30MNK5V4UMqeYjx+aLK+IGlX/ZLKeJws3FRPYQ/qSiAH3vCd3NvrXO81/ADQa0XodAX4EJRcAF7YAVvdz6pjsoYqqBn5ChFsWOg5Af9+KjqhQOgF8XGDcdn3Qbtfdc4/uu+esH7DjAWPlR1RT+jV9CqLRjYSm41661p7rMA6yW67/7ERTCnzWI2y7FEjVXqj4FwEnHk9pYgacfbkBGzezKylxf6OJCbIVudfr2TRGrei/rTeWF6dNf7WC5bx/jskawOK24aFMIY1pbRG7IuHjyge1zrT+M9Fo32U9C7XUqH+6l1rvHF9CmYE6wTVbak3PZwNZTbzM6f3ao4sFySzUSqAwur36qZe7LBo+hHy8RVTqDWspyFt5VwfLF3rkKozsgy+z3yxUWgv0lCbcR8MRQdDNI82lrTmCyOTChM/w1QAPTcJare1NCo3aMeePqRxNgUC+5jAZ0UAc1WYDN9fkcYWeO6Rs0MD+ddUcNXNCllMCwI0Hcpvh7NFPEyMesvuFnxk9CpYF7Z0RRsKgcEJwdt1vYLmXsovFiGQO3FWKcmclVbto5PwtplmCNeByyr2Ocq2/jHNsyj4MKMx7rpDH84P5d4S3B9gHOxwXddTBrHJOMCYdPoBWvaHSKWTF7HQuTlfMstElzKZuGUIJSRtc+tkH3RUk7lxsa+nTPriFqBnlvSON3xfi7m+Z4/jx/3dCMceyOy/mrwjCX3OgVEY0LYu1oC3ciWIKKOCad6CEm/YDaUwVJdxZ8XxBfdOojHFNK8J3vQp6ElhbpZXfHXvL4m2Elw7Yp/ghJPawVFyJ8mCV9flC2Q0FdqoB3pMOmicfH5Ne0aDcluRLIJ/OL6w9NnyOqtiyWibiMs9WKzkijFujsjiIoeH1xAv0EQNVT619wZalLZ6fXrmj/q6lp2+yqjT5LQ6pYESkzqDt37QEp6trmqddExqoDbMbOB6BOP+dWBg3cCwFd86hq0kLsMgcusYk3QhiMr3uQUYocCkfrheG068L4u6EghtxqFs8TGjKHZTQ2NNEq1dXt/QRxImZ0LkFA+0RjrUvpmU9m4cr78o8qk8t93fhj68OQyNpT1urVv+pGkxPsIt1IHj8WFFdxYx/MqY2YzLVYcqji2HBBsDl6HozzOgxRnnPNh8JZVFhhmWI0SLYjupaVYCgo+JWVE0HfMoF74GE214pXdesCE+6YLkZmKZIfuAth4tF1yBTr6VAZIaP+dN6r0yT1lgV6ZLoWocwSd1tqYb5QiK1WptXogkIP5Pt1Uny/v+XNly4ijGR0y0f8ibxS9k9BSXRv2++sI727HsHYfcZ3uNaJxOM/GebxkLFTobCUSx76esPBcVbmK1EvRFtYOAIgzvcDCNF/HI3ZUqTj/hSbAYVr10TPzFWPgzE3tFX5cFgCyoZFX9M1JS0nuN9KkwiZcM2hpS3/2ojlTnNM7+KamvMEpVFO4rgc8JRqdcbD+opaRYsFeyvVS2N493abv3/gcnfcuVX3rcW75DdARoaJQnWVLl7ILQMomgNHCD+FXdKjurvGkpzhAD+HkRYrA6jxg3azEmBBbyb/cIw1yNU616LE+0RoGb4vIv8uu6AXy9UzQpu7TrIcTsNefMhnEJVjEEYgImOsu7kVOiImSYHoALNpkjNb8T7UjAGrBhyWHUQrBmSdxp2DNaUn2mNIMfkPeUbbYwcvs0YIg9ggt0NJU9p8FCq7sGwopQMdLOPdMoN8aZstfw4Xa4z1FKUsTQvm5l7Zv0mR/n1MHmV2Yv74N2vDGSXosZWUkRl7DulWk802zSPvkU4Sl/Bw/D+FvVYrgB0emGcbHWytfzl2eKnz3ufZU/WlOG7qzJAB2RBakZnlezFwrB5aIg3YRFh5Sab+E60GVdMRrjj6oxMcqi+/AR/nTlgp062hSnMRMuOWP8x11YIb1S0sW/Qf/Sbw5OvF1RMm/hkNxV2tQqxjdsH3gL9QXXBYGai4/X22NHFozak7tc9nL2Qb3X1eW1pGPncr+Po49qL7kkka13Xo97ubJyim9ECOQTRPiLnUUoA95H05nuPEhfte11gPsvT7USgoI2OyMSAoWsJexJLRd3iELP70qSKl4Oq/AWPvzmXor8Hpcf5k8e2b21b/tM/nxKqBFq+2LHTrA4R2zTYLMcHKBuVsofnM8KZ0ch0WGrq5KvXULijLqXI093ISi8xISmySQ3y+l25heoGqmCPxg5alpLVyAXU3ssyAxQFMHrkeMUOlQQN2MLn/fdjFzPfLb1Os4xEDv7dmd3EJPoy4mMd+dHunF9SJkfug83NcO9+7CNtbBxk/FHzPnEswGuH0jMQZtY2+fs76njJVsdkXqqww5b1QHCf5H3KCrq+qugK8yk4KvSGtg7c5ThiEWhCjJuBHwYKQosIjN7Mq/AWA2p6JwWTTMYz2PQfjQwudXERbYCt2aJgnq52dW6fRg/QQjsSGTTlxxvG4MErqwGqQjB+aqD2mBZj16twbuW9gqmhOb3VCXiosN4ezuBFCrLgFiqXpQJFUbbIjDDosq6mKUowEAXM/Qt7jp7hhRdCkdFQK/oQtQmXrwB28+oRW1vs6HZ+5SzkMZsKLWTTu+NpGy4ekPLEXa/XdgsMKERzRzXbUvaqEwA2XZfXrBltQLaQ2GKsioeNV+54Cna+wZdZm/61w8X6m0CPIci+J71irZWLlTtxBPZn0RBFTt17Jev+6yuv5Ww4C4tblcu5W1NB/nPkUJ46Ah64CTCqESezyyXff/9K3V2Y1a2x420dCEB/2FkiuZGeIvutTf6K0WeUEOa4svMhdTEbvyZhjpqSu8yGWsjPHIibFgi30BXBhmnSq6CIi2Gb/pgEwUb78krILJwQ2IskTIA5To14VU6sqUdy3ehCxnr4dJSOfPJsFNqBIMkWJPH3UQgeC5583vVj2CBOIkIyG0HRokb0MPKUq68jXd2mUZoSZl9L/xWFXM8JcdrAxRIF8/tHT8u8RNGy9y4n4P7fhvRQGFVjTyLDmseh/QSWTDDU6aBUa72h0dYOgh9zWmvR5kgXHCW1Pj3jebbewHjgD2GRRIR55Twj43kUswYPRV0KTyA7/whimFifJNxKgx/5pYChbRRpCy7UGwUfK9m0UMtMvH/6v+13iGQtzD95/UmgGYudG88Egs6R2f4El1/B0VmOHuWqmFhUSWpPHBmjqhu3jkVQl8aZMN7oZHfOe9PF0gFdQNkU9cX/dcN3UcWILzQ8FKzCOIjb7n++hBOsxY3ir4/Dcxd1i/qBA==,iv:kvnL/cVgBomOUYpI6PJj1gKsuKaWUnY6xfzjidoPrFY=,tag:PbjjjYUN5pI5W10XZ2AOGg==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRVorcnhPMDl5VUt1Nmxm
            Q2lzVFFRSUZmY0xPS2t4NlFHYy82cktUTGxVCjBoSzc1MXRGazRjaHgrK0tteksv
            VEpJTzYwV0sycXk0NnEzSU1TQnQySG8KLS0tIFRuWGg3Tkx2bHI5cDI0Y2tXVWVm
            ZHpFNU1OdWQrZE85dm9jV1B5cWdEdm8K5X/kMC9PeBC0qS8wcDd1TKhv4/CvbL6m
            e0W3bNcoigZn2iQkGMjZGxHQDMz6RypYMyElBKp5L7Pg9l39dPDlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:47:28Z"
    mac: ENC[AES256_GCM,data:pKgxOHNay4Pp/SLXIeLb7XCn9CNR+weyh0JAVIKl3L00caqo87/8AshzGoRXKDtxXiNUxQFwSWvBQRq+cZ0A+6UGF/OKWTu43/08PzqTUfgQ1BenwCeKSiFZct6a0mdWPVhy99rFXxB2fM6ChGyJqG5BGpK9KtPTw3VGMKT1YmQ=,iv:lIjAZ9VyOSa9Qd+03cUF/XcerXAKvhvVbji2iJ3EQ1Y=,tag:UvFIA2J2Es+04uGX4xOv1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nix-kubernetes-gitops-ssh
type: Opaque
data:
    identity: ENC[AES256_GCM,data:T3obunQHL0gQkIjMivDAlQsvFkYensOTHukdwpcY68McOWws4hVPH913xbkyMLS9kmT50RuBDwCr0mtj0p7BrBewTLcj0aG4p9Hu1DuFfWMwhoKNDGe4VQwBav3ytp2hmehOKaK1AmVpk81S/U54yArUJYdWgdCYvejKJsoUgPaEtujGcEJT1IwdtsBsZaWX/AN0bK8w6t0sEMh1NUQwxCelsOSLSkp+D6WtAbCzDyaSBsSawHnrrm2rdCep4wwVTJIhsKfJ85WYDd8DPbljDUergYzx+/XDSKexCv1wYXgPoX4Xop7X9p435V5eCiyQmhnezcfvNd7/DTsVe3nSVYbcCcRt8QQa/ULxxVAu/VuaiJCqMyw55/4njn2lNcqcf7bwZ2iH4kA0LOykPE8M1TmPmj+ALtDS/e5+gqgyrDM4SxW2xePKvvIR8mcWRbX5E5cJwwA77BmfSJmus/CaQYluG0UgpX7NJVK83tA6rnPSBnApnRMXmotIiVf+ZBQcEnP6JhKBfBcquCuEMbyqHFCaM9OiRzHY8FijE6H6EbLlC0bIb2JFpemU45UcHKPo/P2bEdANL8qNgWDmjAGmB03LXqCdHy/vddyGoCaVNw3Znhtt0RTXF79Lg9S3FWlIkL+WTe6dPBUa2Yf/BmhZuxe93Ymc3JBFPNGcuj+j2UKuhv9Wwz5lr53Ko4Bgzb2rgzKJKfpYqWyGVxhp0SvGbqgYIQE=,iv:HWoz+2X+GrTIRUbJtJEkymwSPT5abQaUyqruzv9cFaE=,tag:VJXPCnkfNXM9EapAaGcUHw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1D33LKjxKptxt9A+m84tXyeIcUbqq5ggJA/Eg8HY6ZFvHc6YIVCD6vr9aufhOVbT7iDoBwNUUh4wv61Jtw+UN9AbhgOKi1GT/39pv8YQsgikE75UaAYiNIQfWgM63CaB4szZPyuc3JeMK8kD,iv:yjF8G33YXCjenP543exJqru4Su8qYWEEHs/Q/dStoJ0=,tag:qbid+KV2uwwNX8uAwewrpw==,type:str]
    known_hosts: ENC[AES256_GCM,data:YMDjUfNaGYHr5wt7c3x0LKvvZxJepwwM/vueXH88MkzJVK/rc+9K0PpagaOS+5dg4kQfTgy2c/cP2MfZmlg9E5RqIFYFHfclHZsum847pcbUOJqZ3T/D3bqAdXkzi+tsuqajoUa6HpvHiGv45e/o5hyyUJ/Df6LNyW9u8CYIy2OczqJxhexBSYHETJpsgMuayNEovmGiImts3jpuA+LQpv6IwYe25fRNlDAJHI8n8hCr7gtofGuSgIJAVLWXOpXVUv6BZuUbj5fXnJa/d+Cxz/N7xgOI9UkIAtNs7aSbYKJrpjuc,iv:rT033cbiL35MXwPWsjA5qJBfOQtr6Im6sNivSMgAQx8=,tag:xiQTw8xtXIF1kP5+U9JMFg==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRVorcnhPMDl5VUt1Nmxm
            Q2lzVFFRSUZmY0xPS2t4NlFHYy82cktUTGxVCjBoSzc1MXRGazRjaHgrK0tteksv
            VEpJTzYwV0sycXk0NnEzSU1TQnQySG8KLS0tIFRuWGg3Tkx2bHI5cDI0Y2tXVWVm
            ZHpFNU1OdWQrZE85dm9jV1B5cWdEdm8K5X/kMC9PeBC0qS8wcDd1TKhv4/CvbL6m
            e0W3bNcoigZn2iQkGMjZGxHQDMz6RypYMyElBKp5L7Pg9l39dPDlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:47:28Z"
    mac: ENC[AES256_GCM,data:pKgxOHNay4Pp/SLXIeLb7XCn9CNR+weyh0JAVIKl3L00caqo87/8AshzGoRXKDtxXiNUxQFwSWvBQRq+cZ0A+6UGF/OKWTu43/08PzqTUfgQ1BenwCeKSiFZct6a0mdWPVhy99rFXxB2fM6ChGyJqG5BGpK9KtPTw3VGMKT1YmQ=,iv:lIjAZ9VyOSa9Qd+03cUF/XcerXAKvhvVbji2iJ3EQ1Y=,tag:UvFIA2J2Es+04uGX4xOv1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nix-kubernetes-gitops-dev-sops
type: Opaque
data:
    dev.agekey: ENC[AES256_GCM,data:wV3RweV0TM+5ZOsG9i2BbTPyG/VqxwjPx80nR6nD7oKas6GjdJcbC8JgjdKm98ZA4dbmPojiAkrWm4Um1btrAvzcpQMr7nl4I+QA8MvSeTAqhXNBFBUYzzZxmUlPolxqbAYKbzScF0eU38vqn7hmlLaGcujbhDABaZBlQy49tbOuXUI6QEpNegttjec9k2Zj9NXAjgC3ykbOaYKvkwDrQ7Darl2SflWiB31ylFyR7yqfRIS/a21ck9B1PvrmzKh5Y20NQrVUlF0YOWuBcawHZZgGS10O5aFN81ZNf/b4Z1q3U0rgYBrRhg7AvWxKUL0N+vRKKrtr3OoKOHiX,iv:QLDItyn/DVw2Kt+tdKqC3NW0l4VFYjm/nofwmo3DE2Y=,tag:MfxIXa3R16dX+Q5HPUdsQA==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRVorcnhPMDl5VUt1Nmxm
            Q2lzVFFRSUZmY0xPS2t4NlFHYy82cktUTGxVCjBoSzc1MXRGazRjaHgrK0tteksv
            VEpJTzYwV0sycXk0NnEzSU1TQnQySG8KLS0tIFRuWGg3Tkx2bHI5cDI0Y2tXVWVm
            ZHpFNU1OdWQrZE85dm9jV1B5cWdEdm8K5X/kMC9PeBC0qS8wcDd1TKhv4/CvbL6m
            e0W3bNcoigZn2iQkGMjZGxHQDMz6RypYMyElBKp5L7Pg9l39dPDlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:47:28Z"
    mac: ENC[AES256_GCM,data:pKgxOHNay4Pp/SLXIeLb7XCn9CNR+weyh0JAVIKl3L00caqo87/8AshzGoRXKDtxXiNUxQFwSWvBQRq+cZ0A+6UGF/OKWTu43/08PzqTUfgQ1BenwCeKSiFZct6a0mdWPVhy99rFXxB2fM6ChGyJqG5BGpK9KtPTw3VGMKT1YmQ=,iv:lIjAZ9VyOSa9Qd+03cUF/XcerXAKvhvVbji2iJ3EQ1Y=,tag:UvFIA2J2Es+04uGX4xOv1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
