---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nix-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nix-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nix-developer
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nix-developer
