---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-path-provisioner
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: local-path-provisioner-repo
  releaseName: local-path-provisioner
  maxHistory: 5
  timeout: 5m
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  values:
    replicaCount: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    helperPod:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    storageClass:
      provisionerName: rancher.io/local-path
      defaultClass: true
      defaultVolumeType: local
    serviceAccount:
      name: local-path-provisioner
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    podSecurityContext:
      runAsNonRoot: true
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: 
          - "ALL"
      runAsUser: 65534
      runAsGroup: 65534
      readOnlyRootFilesystem: true
