---

replicaCount: 1


app:
  migrations:
    enabled: true
  env:
    S3__ServiceUrl: https://s3.twcstorage.ru
    S3__BucketName: nix-dev-s3
    S3__Region: ru-1
    S3__ForcePathStyle: "true"

    Uct__Authority: http://mobilebff.backend.svc.cluster.local:8080
    Uct__Audience: platform

    Kinescope__Enabled: "false"
