---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-repo
spec:
  interval: 1h
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    tag: "v1.19.2"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
