apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nix-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nix-developer
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - secrets
      - namespaces
      - nodes
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - events.k8s.io
    resources:
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
  - verbs:
      - delete
    apiGroups:
      - ""
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - acme.cert-manager.io
    resources:
      - orders
      - challenges
