apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nix-admin
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nix-developer
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - services
      - configmaps
      - secrets
      - namespaces
      - nodes
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - events.k8s.io
    resources:
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
  - verbs:
      - delete
    apiGroups:
      - ""
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
      - issuers
      - clusterissuers
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - acme.cert-manager.io
    resources:
      - orders
      - challenges
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-dev-reconciler
rules:
  - apiGroups:
      - image.toolkit.fluxcd.io
    resources:
      - imagerepositories
      - imagepolicies
      - imageupdateautomations
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - ocirepositories
      - gitrepositories
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - patch
      - update
