apiVersion: v1
kind: Secret
metadata:
    name: nix-docker-oci
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JXOp82ssBilaLdAUIJawgOt+ZCu/xXAoscpqiGEot8LhYXZUKyLdrS5nMWBBExibUaEaoAtTcb67j6zcsKz4hVNXu82CX9bpUGO5XxTxwXMnbW/18UcqoLz/XpETLZpyfvXytmYDqE34EW2DRW+4d0XZerwQ0jFegvIBpESu944onUyUpKRAFelSwoycTzpyFdyDs3Zhsf9m4l2GTWjdGFvj278qsyQTEZs/zjB4p2NZAUnWQu9fWDseNhDEP29YTDcfyxGUP9J2ltLLPmpvkk+fGELCfDJSx+ANcz+P5qapo2YWGMnBumiULTJfCfKh8lMbkzaOILjq+ZIouzdITU9xFgyyzJZveFAfFumYyruiI3iWylFgj+AfE5GG87bFY+B5dpNx93S+EIAgOoQ54apM2QrjFuKfnrGcTnagHCHrv69pvcz8/sRiti656VC9knZ3Ks1Z3dLZH3WepU8KRYTdQa5WKLNakUJqQeGPt0ca2jUwCB3pdoGGbee5+T0uSIcDCRCpaGrMG/MFVKm0ysfbXmXhThGunmgm9slOfUAVzarQqTc0ThMYo7FhbQr3z6dil0KyVd3fW6+WudEWyLtjmmn42r7C1IEtbhYOqN88DVCqLXaHwLJ06uvbSJe7qKAlxka2KQ+ykCFU0PeHDMtqVB7ejCThCbxMms7daoMSC0zPBuJge0jd0um1WyRZ43Ex/HwOOdUiVfEHYVPbfPLyVo9UJHO37sfOzXLlrBfaFI3JWO4ox1atcFb2TudgBh0UHe9xn1P8S8+Om5YIHxjxxfD1z+zLkIDA4y3/GRFGuKrrID2dSLZOn+RQ1ajWoeWku/g3gZZHIztSSWEkDos1GpNoV6PQzHIIkg9CWfGXQtUexGkgJcMRb53L8S+YhfWqNSUpbPNUnxigRTD4RlrF4ZK0zd7z47aeOAPpNc8XN2Cd0Op++ge0z8XvIpFyzxXhN1cDIygll2DQix1xJYEzOHzZLHCai5/zIg97SEFpGd8DmFR7ELl3RLbmVJOU5Bl0aJeMbeEDY6PyAuj/zSPlIalAlix2HfbB6wql/Ea4J1W4o8ZennNPsoP+TibZblN9qLz7bdEca7kn8I2UW/8MEMeMyoLvHhuSce1OyTrgJjh007aalKT8LNCi/UOcl45qy+o612/DwpFXbECJFamJrjtR6+wclQbZsE42duH3mLATvF1/rNl+wx7JIANCg0rr6N9ClnvonHjXDc2v0zn7aLNvM5TaD9/vsI+b1SHZQWammGvjy5VSJoGoUjHzVT3vzGRkm8FtvWCtcTsVEGqumgvsw0QJxgD84s+Y+tuy2jUu5YSDH4Jq+txgcSnkl7vrPV0v6b2Dw1b7Ug7F8Utnb4/NunWZGjwfGFfIQ8ierpFkwN6lyRL9T+KbPk8Dn7rHeklNaFoIOTnS8BRjRFqjENFfCb+MmnFxuVfxiurV/rTDtvxbVO+bHPGX4dPuHH6nb1RBP8xOyWTfy96dMVEGOfmd2+ihcXpqgjlA0+ADhK5V/aPV3Ob/SDjmgbLyerSvaae4UP5kHwRhVS7ZWoLSsyitnkIa+suN/uJHxdzPOmKyC9TXEz4M3LXKAQ8IBnaLyV9JASrjNagYBT1DbhfuscVfByHKuLC/wZLZgBUriF3ZS/nYoxqAYdF2kWROsqR0O3GSw/2ynnq6MAuM6jFv2Cn3dv4jphhRuK9CgCGk34eTdN8BW77TvzU9PM+jQkuoqfEIE3hkCAcXQL1AwIzvrgYKsMRpWg2DKWN49ksMCzdEfoNaSM6DEHL6pSI1Zv2jkOL3i5hdxZ5mDEAsjbNHAPT5nB/N9YvHQrb4UCfLuIwwLX6sOlSNV4S4UvuF1DKotfST8Gr3IBWF3XyoODJCsFpBmTKqFvTzNXtEMGp9T6PcdLkL7+1eBfHhPRluputywZ6dLc8NGGrB+d2mZEMY+WqIF1YEIm/tPBR3cBJMOFAH1D42BT8VaP0Q4DS47jPkciUmAC88uM4rOA9k0KhPWzZQ06Jb+ZpJuoD84qH2nBTleJW+Vq9asSfXXQCBQ+xpVzkE+abML9uJLqUuEO99ulENkaDPY0Mrwju0JIkzeC/nSr3tPQZ8j1E7eTHH0lvSILUAHD85Y0IIk73TqRpfdMt/VL2wgc1Dpas6w2u4/2YI0inzHhNZDsw2FJeKyPbrxwv8Z7YezoZ5rHiOX7KE3a5B3sSb7IgKUE3ctFa0CyZH2UfAwVD5G+kcQ1hl96R8dpe5SOAlM8+kF3QtEsewR+NguaZ9Byzdq9sqmeIEVfC7ZTSxoAktXlsxvgMLTM1iaPrGOj2N2lRgOcWY+eZUL7FZbBm/rZP0qYclbtpXduxvdpVo5L9fJBU08so526+898dOm9EHIJMA93UP5swti+GFoHPS8I+MbyahBbCHxei4OTeDPhz2ESw1kC2ticVHx55WSM9qatfcHqzQaWQUjjS0NaPoaTMs39R73nG+xM5/VsJYLmoSfqNXv6VuengHQYTaT8vL8DQer7Yq9zXJdUotDcwoROnLPgalvenybj6jsZyItUMYTBP5g5XxdzLM9Iyh/4M84itNvLBD3y5rN9XRhezB2jjnIekOuLVwYLS3e4VyN2kh4Jr9hyOM13g98y77lYl3k7834C2NbEmUwviAyx2+c8/6zRg3Ew2I4nGiFGm2RBRRXuB+M9kHbNtVbk0ohXcUjijtn92wGmhVqwhpMbPmqc8VGMx8Rt/I1l+PSVxemU5hiLG0QnH8JVl0PzGhlzomyhDgtPlHa7jnai76coEsSORbt7U855aLHtmrGD5Kf1qBt2pshiWVliI42n5DLD1MbmhHaia26fvQpgZsfGMyGqKyirnneuiXuy1KvAYnG3/3nAZfzAHnH5HofCHpOjXQXNMWaiDGD4rDtkP3yBjZR441MP1Bvz3yQipE0+ClmwXmnYdc649wrD7nLAs/0k+LjJwM8Jg3Npy7OWsoakcsV6M/RKfF0pVZEQQmoq7nXl+GfZ+lU0NR+1Y1793l2LeqKBI37aR+rn4EhZGC2XBLGKIeuIBgjSLqejP/CvcgHMO/Ps3dwUi8mCkmY331P8IidSHVMaUQuv053QPRC0e/Mt27CNLMF47lwB/qVrR3lHIpNbkMIrd3R1Vz4qkCoS7S06NS6F1K/tzOLcJlD4iYB4EpGnWh0fYfeQOTIzwqIllYLaqzyHB+/OdWYbT5TS9cSRevr9EoNlg+GymRy2CdEl8jnYnnm/RoyfjJKYNv1/7Qd8DNwRGRwSz3W3n4i64Wuy3fu7MmlnZaK/TJYZGAhBdMQw==,iv:Z91HwbCWVG/KA3Fk1t/Nh5JnqylOrZaUzbuyvnmL5fw=,tag:zi4SU0cOYSCllY9a/98V/Q==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cW5icEJ4K0xZUC9sem9J
            a3JSWWJJSUhaS3k1UmFhZVhFYTY2QjJEOEhzCk9wQklmNVZSVUp3RG5YWkRDRGU1
            Zllxc1RkM3grc3VsNnJ5ZzNqdDBnVlUKLS0tIGJjWGJiKzQrYUN6emR4eTkxaTN4
            MmJDeTdjZkFJQjlHaHdWS0U1d1FUVmcKqlEUZVJ7nlBEcTpVGAJGPi0rssZbVx/N
            uqf00axr6iny6K4WESkIMNsiUrqINy/DcIzeD5FC6O7WO/X1qXth4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T21:13:07Z"
    mac: ENC[AES256_GCM,data:KCG6F2LoZiQ8nRu6AP9f3PuopiXslVH7PCF6Zy5RulYBwzr1vklVXKzess+Vv6Ria+gS5ZFQhmcdcQOrK9DXjOplEn4B7ys+Gb0mLxlU95z4P/PgbsWxNkttagp7v63gab63IwPiyexJmhyMnMsnupq014DDoUMk3EL1FgdN7g8=,iv:/bhiepwfIJUJbmLz03BnwjvOqeqtLd5S1lN/Fxg1X/k=,tag:TC7JzWN19OmzviDBeduq6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nix-kubernetes-gitops-ssh
type: Opaque
data:
    identity: ENC[AES256_GCM,data:O0JwptkVQWgYcS554jQAxgCt+eV+dJ1w9tA72QvgO1c2x/cYapgR2s3EtCy+x899VivWtNzgesMYPNS3bZN35CVN6dALF8gj8Ikfp4uc1U4c8rghPNlYCUmozYZkaFCalxKNHTEZfkS25lhRdoSTnfzFDE/fxF/XbpoKm/2XoNmjIR90dyms39uUxfbEtr3Tjbm9YeW8ArJdk79uhj8emy4RSeLFzd9W0zkfLVyv7zwhzDODlsQUwSrpJX5uWYVDyk60ZIwhkxtZ3nYJxVngbPjzUFOQyd5Irtx3p4Rqar4DZ7I3ERnEekC4iNX38Sb1jI+fA9WcpYr8EkJSbiFIYCMdlnTRnNwKDaEZzsUGN8k6FFRliRp19xwgVrDFaJMvMo2c7hLzZLrh5cfHW/F4SoMKE7BQHy9iHybmDn6UdcDl1/ANY+/DWXqwVoORpXDgDNXc6VoKdmIR4YvhQSM7SwZ2NUd1qzY288taZVy57nJmIcgniHGCl2v3knUXNVO2s4vnSIIhAXsTBqB8sps6XG0KhzZvgmOYq8kS064q3q/hSFWbbTVmKRHfnths0KHPmwWrHWUzjrTNzxvjOW6EakJjbNcgeWfEfQU/6JI37feVwAZiyMJ0jd1nL5eh+sMyLx96gEYmvS8lljEcaifIZ7IzWFjsJueOiFm0xNbGIgzwoTFvLkmOQnVmG+B2pp52vB8aB7bRO/HQZZA3uBEmI8bQjv0=,iv:2Q21wX5u2ttcNv821B/HApORVdN7pEXEzhRojpvxLbQ=,tag:kpLEUDEqYiqfW4sdVCAbHw==,type:str]
    identity.pub: ENC[AES256_GCM,data:TQuVZqzuBFad1QB0anvhrNK/khplQsTCoaG/AQjg0PBJCTex0Aa47KW3E2IpBj9QQd4Gs1pOrR1zjG6aRqAr/8DGwpnqTk9TZAvB6BQrUMmv5FgW8KZsuU7zpwLxfMNjf8bMpRxkONnkq4jJ,iv:vDzK8l2AaND1mHqg2kY/Yss4a8IrvcPu/E/4S6mBRJc=,tag:VvfO/BvuDlMdTpDRuDKs5g==,type:str]
    known_hosts: ENC[AES256_GCM,data:Xiveuwq3nKcevW6DKEbc4mezM6rnOnfA2usR8o81wHBtud3JC4RfPTWZbr4XhYi1vZEAar9mNpWH6K2Mt7EDdfYs6Anx0fh0gehbxVKYP7YcVLqznlLpkwYk74Gcf+VJFjOHCGTIeQRkEXSujAfK8vMJMSPROVcyWndS8oBQ0JKgddwS4bvPuErXlS6F6rgWQ40eYGwmD2RSgSUvA0sDRegr7looOLkStxN2PWydvaqj4z1mIFs+ZKk4YRgX5/24wK2h6jV371VSMsnYg8QRqLfYnFm/QVwpkTecOD3oFpHpnsqu,iv:mo0UdqGHA3cyFAwbHx75mFRDkxvKLKNKL9TdcVWDVro=,tag:H5Ow84EYEeU/MzCL58I/Mw==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cW5icEJ4K0xZUC9sem9J
            a3JSWWJJSUhaS3k1UmFhZVhFYTY2QjJEOEhzCk9wQklmNVZSVUp3RG5YWkRDRGU1
            Zllxc1RkM3grc3VsNnJ5ZzNqdDBnVlUKLS0tIGJjWGJiKzQrYUN6emR4eTkxaTN4
            MmJDeTdjZkFJQjlHaHdWS0U1d1FUVmcKqlEUZVJ7nlBEcTpVGAJGPi0rssZbVx/N
            uqf00axr6iny6K4WESkIMNsiUrqINy/DcIzeD5FC6O7WO/X1qXth4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T21:13:07Z"
    mac: ENC[AES256_GCM,data:KCG6F2LoZiQ8nRu6AP9f3PuopiXslVH7PCF6Zy5RulYBwzr1vklVXKzess+Vv6Ria+gS5ZFQhmcdcQOrK9DXjOplEn4B7ys+Gb0mLxlU95z4P/PgbsWxNkttagp7v63gab63IwPiyexJmhyMnMsnupq014DDoUMk3EL1FgdN7g8=,iv:/bhiepwfIJUJbmLz03BnwjvOqeqtLd5S1lN/Fxg1X/k=,tag:TC7JzWN19OmzviDBeduq6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: nix-kubernetes-gitops-dev-sops
type: Opaque
data:
    dev.agekey: ENC[AES256_GCM,data:Fr7+cLCwdQm8ijin2eeeaNlYzEMRqv2/PM+NYesWsvZmD56xRmHU13Qcps4kC+parci6swW7xE5D5qw1TcF+41mO4rPl5eJbWTm5Go7pEuRBsu6DGRLWvAQ/4G1/Eind+VBMGqOKzsoEYrN7afQvYIoZQLtcGYa8rWyqDZq3C+s3/4dR0SFZvrzRzOHB+gC57G33NT6jDOfVTLGNXeqgmaNQUHjqg5/hovD04HrpoY+X0P7b4NWQ/uqYMb56cWRXU8kEnmUls1cYSQvpCgdrq5FELqvsYfH1QuKL3W/0FzHhYUbSpIUsKiPyMvlcLG/2hkGAK58RM2EhzyYx,iv:PeB07NMhT/mwkPTBDhbId6EoG3UDTGElVE9uQUW/dPk=,tag:YbBClDAjuLhNjXDyo45i8w==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cW5icEJ4K0xZUC9sem9J
            a3JSWWJJSUhaS3k1UmFhZVhFYTY2QjJEOEhzCk9wQklmNVZSVUp3RG5YWkRDRGU1
            Zllxc1RkM3grc3VsNnJ5ZzNqdDBnVlUKLS0tIGJjWGJiKzQrYUN6emR4eTkxaTN4
            MmJDeTdjZkFJQjlHaHdWS0U1d1FUVmcKqlEUZVJ7nlBEcTpVGAJGPi0rssZbVx/N
            uqf00axr6iny6K4WESkIMNsiUrqINy/DcIzeD5FC6O7WO/X1qXth4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T21:13:07Z"
    mac: ENC[AES256_GCM,data:KCG6F2LoZiQ8nRu6AP9f3PuopiXslVH7PCF6Zy5RulYBwzr1vklVXKzess+Vv6Ria+gS5ZFQhmcdcQOrK9DXjOplEn4B7ys+Gb0mLxlU95z4P/PgbsWxNkttagp7v63gab63IwPiyexJmhyMnMsnupq014DDoUMk3EL1FgdN7g8=,iv:/bhiepwfIJUJbmLz03BnwjvOqeqtLd5S1lN/Fxg1X/k=,tag:TC7JzWN19OmzviDBeduq6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
