---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: keycloak
imagePullSecrets:
  - name: nix-docker-oci
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: frontend
imagePullSecrets:
  - name: nix-docker-oci
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: backend
imagePullSecrets:
  - name: nix-docker-oci
