---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nix
spec:
  valuesFrom:
    - kind: ConfigMap
      name: nix-values
      valuesKey: values.yaml
    - kind: Secret
      name: nix-secrets-values
      valuesKey: secrets.values.yaml
