apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gateway-chart-repo
spec:
  interval: 1h
  url: oci://nix-docker.registry.twcstorage.ru/helm/apps/back/gateway
  ref:
    tag: "1.0.0002" # {"$imagepolicy": "flux-system:gateway-chart-release:tag"}
  secretRef:
    name: nix-docker-oci
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
