---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: apps-image-update-automation
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: nix-kubernetes-gitops
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(images): automated update [skip ci]

        Automation: {{ .AutomationObject }}

        Changes:
        {{ range $filename, $objects := .Changed.FileChanges -}}
        - {{ $filename }}
        {{- range $resource, $changes := $objects }}
          {{ $resource.Kind }}/{{ $resource.Name }}:
          {{- range $_, $change := $changes }}
            {{ $change.OldValue }} -> {{ $change.NewValue }} (policy: {{ index (splitList ":" $change.Setter) 1 }})
          {{- end }}
        {{ end }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps
    strategy: Setters
