---
- op: replace
  path: /spec/chart/spec/version
  value: "0.39.0"
- op: add
  path: /spec/valuesFrom
  value:
    - kind: ConfigMap
      name: headlamp-values
      valuesKey: values.yaml
    - kind: Secret
      name: headlamp-secrets-values
      valuesKey: secrets.values.yaml
