---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  chart:
    spec:
      version: "0.41.0"
  valuesFrom:
    - kind: ConfigMap
      name: headlamp-values
      valuesKey: values.yaml
    - kind: Secret
      name: headlamp-secrets-values
      valuesKey: secrets.values.yaml
