app:
    secrets:
        env:
            Keycloak__ClientId: ENC[AES256_GCM,data:No+L2HJ46EeQXzQ=,iv:YjDLY2dGFP6XTVObk6h6WqX6syZYrZd+c6RNhWV/QSw=,tag:QJJqI7g+mAw3CxE8sjBFCA==,type:str]
            Keycloak__ClientSecret: ENC[AES256_GCM,data:yBPCD/Ps2cG/H7XYbgEPJTcZYCQiluMPXycMNPE6hyQ=,iv:DQabkkdCWAqYglsw4Gx9B44WNVRplk7YbuF1GFHPn+U=,tag:4tQKbnlI9rYbev7mpYquyg==,type:str]
sops:
    age:
        - recipient: age1l535lzqsjcgzlpt4wy7galk8hhx8zw0wezqh46xaxp3n3fuakymsdnq80c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQc0NacDhmTlREVDJNbm9K
            MEgrVnBFYi9VTEt5bWxoeG1Fcm12YnE0YjFBCjI1TGJUNXd6b2RoTkpNVk1RZEw4
            dzZyNkVRSzNKb1JZcEdMdTF2UDlEQUUKLS0tIGdHV1c4WmthbUFxMWxUUFNJNmx6
            UzJpeVl0SHhBVjhQekpPVC9uWWh4ZVUKVIlAHcL1Q1CMWVifCtaScAKak5VbP/ad
            6oSRShrSBTnEurp691+vc95UTC+24+6nUrMlgvW19IkswTOqXPK+oQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T15:52:22Z"
    mac: ENC[AES256_GCM,data:hk0cT8l4oKifi7rW8/NAdrY4wWjIr8aPPG5OJItShy6DytRUwPexGHDASmxP4UiXxuIBjgNvGfkiIG56KVyq4OPmZdYG5DlhNRPNMGkGIHBAqGnCH39m3Sm42QkAB6DCw3q+djYOyVDUlMRXxMBTEGMJjOx99Q2XUG4jcvN9frc=,iv:+gzWxb90YnEqFwE+9d2HtidNiaPYMzS+xPSm9wRRUqo=,tag:eLO/ggmn8SZP+dEvwKlocw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
