---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: flux-operator-repo
  releaseName: flux-operator
  maxHistory: 5
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 1
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
