---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nix
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: nix-chart-repo
  releaseName: nix
  maxHistory: 5
  timeout: 5m
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
