---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: gateway-chart-latest
spec:
  imageRepositoryRef:
    name: gateway-chart
  policy:
    semver:
      range: ">=1.0.0000-0 <2.0.0000"
