---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
spec:
  interval: 5m
  chart:
    spec:
      chart: valkey
      sourceRef:
        kind: HelmRepository
        name: valkey-repo
      version: "0.9.3"
  releaseName: valkey
  maxHistory: 5
  timeout: 5m
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  values:
    podSecurityContext:
      fsGroup: 10001
      runAsUser: 10001
      runAsGroup: 10001
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 10001
  dependsOn:
    - name: local-path-provisioner
      namespace: local-path-provisioner
