---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak-infra
spec:
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-infra-values
      valuesKey: values.yaml
    - kind: Secret
      name: keycloak-infra-secrets-values
      valuesKey: secrets.values.yaml
